version: "3.3"

services:

  social-network:
    build: .
    container_name: social-network
    restart: always
    environment:
      FLASK_APP: cli_app.py
      ENV: ${ENV}
      SECRET_KEY: ${SECRET_KEY}
      DB_HOST: ${DB_HOST}
      SLAVE_HOST: ${SLAVE_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_DATABASE: ${MYSQL_DATABASE}
      TARANTOOL_HOST: ${TARANTOOL_HOST}
      TARANTOOL_PORT: ${TARANTOOL_PORT}
      TARANTOOL_USER_NAME: ${TARANTOOL_USER_NAME}
      TARANTOOL_USER_PASSWORD: ${TARANTOOL_USER_PASSWORD}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
    volumes:
      - "./logs:/usr/src/logs"
      - "./app:/usr/src/app"
      - "./tests:/usr/src/tests"
    networks:
      - shared
    ports:
      - ${SOCIAL_NETWORK_PUBLIC_PORT}:8000
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - "./volumes/db:/var/lib/mysql"
      - "./volumes/db_dump:/dump"
      - "./conf/mysql/master.cnf:/etc/mysql/conf.d/my.cnf"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - shared
    ports:
      - ${DB_PUBLIC_PORT}:3306
  tarantool:
    image: tarantool/tarantool
    container_name: tarantool
    volumes:
      - "./volumes/tarantool:/var/lib/tarantool"
      - "./conf/tarantool:/opt/tarantool"
    environment:
      TARANTOOL_USER_NAME: ${TARANTOOL_USER_NAME}
      TARANTOOL_USER_PASSWORD: ${TARANTOOL_USER_PASSWORD}
    networks:
      - shared
  mysql-tarantool-replicator:
    build: ./mysql-tarantool-replicator
    container_name: mysql-tarantool-replicator
    networks:
      - shared
  broker:
    image: redis:latest
    restart: always
    container_name: broker
    volumes:
      - ./volumes/broker/:/data
    networks:
      - shared
  celery:
    build: .
    command: celery worker -A app.app.celery
    restart: always
    environment:
      FLASK_APP: cli_app.py
      ENV: ${ENV}
      SECRET_KEY: ${SECRET_KEY}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_DATABASE: ${MYSQL_DATABASE}
      TARANTOOL_HOST: ${TARANTOOL_HOST}
      TARANTOOL_PORT: ${TARANTOOL_PORT}
      TARANTOOL_USER_NAME: ${TARANTOOL_USER_NAME}
      TARANTOOL_USER_PASSWORD: ${TARANTOOL_USER_PASSWORD}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
    depends_on:
      - social-network
      - broker
    volumes:
      - "./app:/usr/src/app"
    networks:
      - shared

networks:
  shared:
    driver: bridge
