version: "3.3"

services:

  social-network:
    build: .
    container_name: social-network
    restart: always
    environment:
      FLASK_APP: cli_app.py
      ENV: ${ENV}
      SECRET_KEY: ${SECRET_KEY}
      DB_HOST: ${DB_HOST}
      SLAVE_HOST: ${SLAVE_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - "./logs:/usr/src/logs"
      - "./app:/usr/src/app"
      - "./tests:/usr/src/tests"
    networks:
      - shared
    ports:
      - ${SOCIAL_NETWORK_PUBLIC_PORT}:8000
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - "./volumes/db:/var/lib/mysql"
      - "./volumes/db_dump:/dump"
      - "./conf/mysql/master.cnf:/etc/mysql/conf.d/my.cnf"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - shared
    ports:
      - ${DB_PUBLIC_PORT}:3306
  netdata:
    image: netdata/netdata
    hostname: localhost
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  shared:
    driver: bridge
