version: "3.3"

services:

  social-network:
    build: .
    container_name: social-network
    restart: always
    environment:
      FLASK_APP: cli_app.py
      ENV: ${ENV}
      SECRET_KEY: ${SECRET_KEY}
      DB_HOST: ${DB_HOST}
      SLAVE_HOST: ${SLAVE_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - "./logs:/usr/src/logs"
      - "./app:/usr/src/app"
      - "./tests:/usr/src/tests"
    networks:
      - shared
    ports:
      - ${SOCIAL_NETWORK_PUBLIC_PORT}:8000
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - "./volumes/db:/var/lib/mysql"
      - "./volumes/db_dump:/dump"
      - "./conf/mysql/master.cnf:/etc/mysql/conf.d/my.cnf"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - shared
    ports:
      - ${DB_PUBLIC_PORT}:3306
  slave:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - "./volumes/slave:/var/lib/mysql"
      - "./volumes/slave_dump:/dump"
      - "./conf/mysql/slave.cnf:/etc/mysql/conf.d/my.cnf"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - shared
    ports:
      - ${SLAVE_PUBLIC_PORT}:3306
  slave2:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - "./volumes/slave2:/var/lib/mysql"
      - "./volumes/slave_dump:/dump"
      - "./conf/mysql/slave2.cnf:/etc/mysql/conf.d/my.cnf"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - shared
    ports:
      - ${SLAVE2_PUBLIC_PORT}:3306
  tarantool:
    image: tarantool/tarantool
    container_name: tarantool
    volumes:
      - "./volumes/tarantool:/var/lib/tarantool"
      - "./conf/tarantool:/opt/tarantool"
    environment:
      TARANTOOL_USER_NAME: ${TARANTOOL_USER_NAME}
      TARANTOOL_USER_PASSWORD: ${TARANTOOL_USER_PASSWORD}
    networks:
      - shared
  tarantool-mysql-replicator:
    build: ./conf/mysql-tarantool
    container_name: tarantool-mysql-replicator

networks:
  shared:
    driver: bridge
